apiVersion: v1
kind: Service
metadata:
  name: demo-spring-service
spec:
  selector:
    app: demo-spring
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 8080 # Internal container port where the application runs
      nodePort: 30007  # NodePort to access the service externally
  type: NodePort
